// SPDX-License-Identifier: CC0-1.0
// Public-domain example code (CC0) - see LICENSE. The CAS BACnet Stack itself is
// a separate, commercially licensed product and is not covered by CC0.
// =============================================================================
// BACnet Profile Example - B-ACCR (Access Control Credential Reader) - C++
//
// This example implements the BACnet "B-ACCR" (Access Control Credential
// Reader) device profile with the CAS BACnet Stack. It is the B-SS (Smart
// Sensor) baseline plus the one object family that makes it a credential
// reader, and this series' first demonstration of SubscribeCOV.
//
// A B-ACCR (ANSI/ASHRAE 135, Annex L.7 Miscellaneous) reports the credential
// presented at a door and pushes that report to subscribers instead of making
// every client poll:
//
//     DS-RP-B     - respond to ReadProperty requests
//     DS-WP-B     - allow other devices to WriteProperty (Out_Of_Service, here)
//     DS-COV-B    - execute SubscribeCOV / ConfirmedCOVNotification /
//                   UnconfirmedCOVNotification                          (NEW)
//     DS-ACCDI-B  - serve a Credential Data Input object                (NEW)
//
// plus discovery (Who-Is/I-Am, Who-Has/I-Have). It does NOT require WPM,
// alarms/events, scheduling, or trending, so this example leaves those off.
//
// THIS REPO IS CANONICAL FOR F-COV. Every later example in the series that
// needs SubscribeCOV copies this pattern: SetPropertySubscribable on the
// property being watched, SetCOVSettings to bound the subscription table,
// and a value-changing action that calls BACnetStack_UpdateValue so the stack
// evaluates and fires the notification. Read the comments below closely if
// you are that later example.
//
// The device keeps the three read-only sensor objects from B-SS and adds a
// Credential Data Input object - the thing a door reader actually reports.
// Each object has a colour name (the convention shared across this series):
//
//     Device 389012              "Chipkin Example B-ACCR"     (instance configurable with --deviceID)
//     Analog Input  1             "Bronze"      (REAL, degrees Celsius; read-only, COV-subscribable)
//     Binary Input  1             "Emerald"     (active / inactive; read-only)
//     Multi-State Input 1         "Hot Pink"    (state 1..3; read-only)
//     Credential Data Input 1     "Flax"        (AuthenticationFactor; read-only, COV-subscribable)
//     Network Port 1              "Vermilion"   (the BACnet/IP port - required)
//
// CREDENTIAL DATA INPUT'S Present_Value IS NOT A SCALAR. Clause 12.36 types it
// BACnetAuthenticationFactor, a SEQUENCE of {format-type, format-class,
// value [OCTET STRING]}. The CAS BACnet Stack serves it by wrapping the
// application's existing OctetString callback: register the credential's raw
// bytes there and the stack assembles the SEQUENCE around them (format-type /
// format-class come back as the stack-side default 0 - see
// BACnetBusinessLogic.h's UseCallbackGetPropertyAuthenticationFactor). This
// is a real, verified customer-DLL capability (stack PRs #166/#167), not a
// gap: TODO.md has nothing to say about it.
//
// Supported_Formats (REQUIRED, cl. 12.36) is a different constructed type -
// BACnetAuthenticationFactorFormat, an ARRAY of {format-type, vendor-id?,
// vendor-format?} - and needs its OWN dedicated callback
// (RegisterCallbackGetPropertyAuthenticationFactorFormat) because, unlike the
// one-field AuthenticationFactor, it has three independently-meaningful
// fields that no single primitive callback can carry.
//
// Update_Time (REQUIRED, cl. 12.36) is BACnetTimeStamp-typed. The stack wraps
// it from the application's existing Time callback (no dedicated callback
// needed) - this closes the exact hole that used to make SubscribeCOV on a
// CDI's initial notification incomplete.
//
// To be a conformant BACnet device (Protocol_Revision 24) each object must
// expose its full set of REQUIRED properties. Most are generated by the stack
// (Object_Identifier, Object_Type, Status_Flags, Object_List, Protocol_*).
// Event_State is NOT generated - with no alarming configured it simply reads
// its datatype default of normal(0), correct by coincidence, not because the
// stack computes it. The handful that the application must supply are served
// by the Get*Property callbacks below, and a few are turned on with
// SetPropertyEnabled.
//
// Interactive keys (handled by the shared helper): h = help, q = quit,
// up/down = nudge Analog Input 1 by +/-1.1 AND simulate a new credential
// presentation on Credential Data Input 1, firing a COV notification on both
// (see "the F-COV pattern" in main() below). Command line: --port <n>,
// --deviceID <n>.
//
// All the UDP/stack plumbing lives in common/CASExampleHelper so this file can
// stay focused on the BACnet logic.
// =============================================================================

#include "CASExampleHelper.h"
#include "CASBACnetStackExampleConstants.h"
#include "CASBACnetStackAdapter.h" // the CAS BACnet Stack C API (BACnetStack_*); call
                                    // LoadBACnetFunctions() before any BACnetStack_* call -
                                    // see the top of main() below.

#include <stdio.h>
#include <string.h>
#include <string> // std::string - g_firmwareRevision, built at runtime; see its own comment below
#include <time.h>

#if defined(_WIN32)
#include <windows.h> // Sleep()
#else
#include <unistd.h>  // usleep()
#endif

using namespace CASBACnetStackExampleConstants;

// -----------------------------------------------------------------------------
// 0. Constants not (yet) in the shared common/CASBACnetStackExampleConstants.h
//
// common/ is content-identical across the whole example series (owned by
// B-SS-CPP, synced with tools/sync-common.sh) - so a constant this example
// alone needs is defined locally instead of added there. See B-ACDC-CPP's
// main.cpp for the same pattern with its Access Door constants.
// -----------------------------------------------------------------------------

// Credential Data Input (source/BACnetObjectType.h: credentialDataInput = 37).
static const uint16_t OBJECT_TYPE_CREDENTIAL_DATA_INPUT = 37;

// Properties this profile needs that common/ does not yet define
// (source/BACnetPropertyIdentifier.h).
static const uint32_t PROPERTY_IDENTIFIER_RELIABILITY = 103;
static const uint32_t PROPERTY_IDENTIFIER_UPDATE_TIME = 189;
static const uint32_t PROPERTY_IDENTIFIER_SUPPORTED_FORMATS = 304;

// BACnetReliability (source/BACnetReliability.h).
static const uint32_t RELIABILITY_NO_FAULT_DETECTED = 0;

// BACnetAuthenticationFactorType (source/BACnetAuthenticationFactorType.h).
// simple-number32: a 32-bit numeric card/credential ID - the simplest faithful
// representation of "the reader saw an ID number", which is what our octet
// payload below actually carries.
static const uint32_t AUTHENTICATION_FACTOR_TYPE_SIMPLE_NUMBER32 = 4;

// SubscribeCOV (source/BACnetServicesSupported.h: subscribe-cov = 5). Not yet
// in common/ because B-ACCR is the first example in the series to enable it.
static const uint32_t SERVICE_SUBSCRIBE_COV = 5;

// -----------------------------------------------------------------------------
// 1. Example + device configuration
// -----------------------------------------------------------------------------
static const char* APP_NAME = "BACnet B-ACCR (Access Control Credential Reader) Example - C++";
static const char* APP_VERSION = "1.0.2";

// The device instance. BACnet requires this to be configurable, so it defaults
// to 389012 (each profile example in the series has its own default, so several
// examples can run on one subnet) and can be overridden with --deviceID. Keep
// it configurable in your product: it must be unique across the internetwork.
static uint32_t g_deviceInstance = 389012;

// ---- Device identity: CHANGE ALL OF THIS BEFORE YOU SHIP --------------------
// Everything in this block is read by clients and shown to the operator in every
// discovery tool on the network. Left as-is, your product will appear on a real
// site announcing itself as a Chipkin demo. None of it is cosmetic:
// Object_Name must be unique across the BACnet internetwork, and Model_Name /
// Vendor_Identifier are what a building operator uses to identify your device.
//
// This block is the ship checklist. Every constant below has a note saying what
// to change it to; nothing here is safe to leave at its example value.
// -----------------------------------------------------------------------------

// Your BACnet Vendor Identifier. 389 = Chipkin Automation Systems; change this
// to YOUR company's vendor ID before shipping a product. Vendor IDs are assigned
// by ASHRAE - request one (free) at https://bacnet.org/assigned-vendor-ids/.
// Update VENDOR_NAME below to match.
static const uint32_t VENDOR_IDENTIFIER = 389;

// The Device object's Object_Name.
//
// THIS IS THE ONE THAT WILL BITE YOU. Object_Name must be unique across the
// whole BACnet internetwork, and here it is a COMPILE-TIME constant. The device
// instance is runtime-configurable via --deviceID, so it is easy to ship two
// units, configure their instances correctly, and still have BOTH announce
// Object_Name "Chipkin Example B-ACCR" - a spec violation, and a hard BTL failure. In a real
// product Object_Name must be per-unit configurable too: derive it from a serial
// number, DIP switches, a config file, or add a --deviceName argument.
static const char* DEVICE_NAME = "Chipkin Example B-ACCR";

// The Device object's Description. Change it to what YOUR device actually is;
// this string describes this tutorial.
static const char* DEVICE_DESCRIPTION =
    "Chipkin CAS BACnet Stack example - B-ACCR (Access Control Credential "
    "Reader) profile. Demonstrates DS-RP-B + DS-WP-B + DS-COV-B + DS-ACCDI-B: "
    "a Credential Data Input object reporting the last credential presented, "
    "pushed to subscribers with SubscribeCOV.";

// Device identity strings (read by clients, and used to populate I-Am).
//   VENDOR_NAME - your company name; it must match VENDOR_IDENTIFIER above.
//   MODEL_NAME  - your model designation. This is what a building operator reads
//                 to identify your device in a discovery tool.
static const char* VENDOR_NAME = "Chipkin Automation Systems";
static const char* MODEL_NAME = "CAS BACnet Stack Example - B-ACCR";

// Application_Software_Version (12) is just APP_VERSION - one source of
// truth, so it can never drift from what --version/the startup banner
// prints (it did drift: this used to be a separate hardcoded "1.0.0"
// constant nobody updated across several patch releases - found via a real
// device read, not code review, by someone actually testing the built
// device's Device object properties).
//
// Firmware_Revision (44) is meant to name the underlying platform/stack,
// not this example's own version - built at runtime from the CAS BACnet
// Stack's own BACnetStack_GetAPIMajorVersion()/etc. (the same 4 calls
// common/CASExampleHelper.cpp's PrintVersion() already uses for the
// startup banner's "CAS BACnet Stack version: X.Y.Z.W" line), so it can
// never go stale either - see g_firmwareRevision below, populated once
// right after LoadBACnetFunctions() succeeds (those functions are what
// the version getters themselves are, so they must be loaded first).
static std::string g_firmwareRevision;

// The sensor objects (all instance 1) and their colour names.
static const uint32_t ANALOG_INPUT_INSTANCE = 1;       // "Bronze"
static const uint32_t BINARY_INPUT_INSTANCE = 1;       // "Emerald"
static const uint32_t MULTI_STATE_INPUT_INSTANCE = 1;  // "Hot Pink"
static const uint32_t MULTI_STATE_INPUT_NUMBER_OF_STATES = 3;

// The Credential Data Input object - the object that makes this a B-ACCR.
static const uint32_t CREDENTIAL_DATA_INPUT_INSTANCE = 1;  // "Flax"
static const uint32_t CREDENTIAL_VALUE_LENGTH = 4;          // bytes (simple-number32)
static const uint32_t CREDENTIAL_SUPPORTED_FORMATS_COUNT = 1;

// The Network Port object - every BACnet device must have one. It represents
// the BACnet/IP port this device communicates on.
static const uint32_t NETWORK_PORT_INSTANCE = 1;       // "Vermilion"
static const uint32_t MAX_APDU_LENGTH = 1476;          // BACnet/IP APDU length

// BACnet/IP addressing the Network Port object reports. The IP address and
// subnet mask are filled in at start-up from the host's primary interface; the
// gateway is left unset (0.0.0.0) for this example. The stack also uses
// IP_Address + BACnet_IP_UDP_Port to build the port's MAC_Address automatically.
static uint8_t g_ipAddress[4] = { 0, 0, 0, 0 };
static uint8_t g_ipSubnetMask[4] = { 0, 0, 0, 0 };
static uint8_t g_ipDefaultGateway[4] = { 0, 0, 0, 0 };
static uint16_t g_bacnetIpUdpPort = 47808;

// Analog Input 1's live present value (degrees Celsius). Starts at 21.5 and is
// nudged by the up/down arrow keys. A real sensor would update this from
// hardware instead.
static float g_analogInput1Value = 21.5f;

// Whether each input-family object has been taken Out_Of_Service by a client's
// WriteProperty (DS-WP-B demo - see SetPropertyBool below). None of this
// profile's objects has any other profile-writable property.
static bool g_analogInputOutOfService = false;
static bool g_binaryInputOutOfService = false;
static bool g_multiStateInputOutOfService = false;
static bool g_credentialDataInputOutOfService = false;

// Credential Data Input 1's live state: the last "card" presented at the door,
// as a raw 4-byte value (simple-number32, big-endian) - the OCTET STRING the
// AuthenticationFactor wraps around - and the wall-clock time it changed. A
// real reader would fill these in from its physical reader hardware instead of
// the up/down keys below.
static uint32_t g_credentialValue = 0x00A1B2C3;
static time_t g_credentialUpdateTime;

// -----------------------------------------------------------------------------
// 2. Property "get" callbacks
//
// The stack calls these when a client reads a property. For each data type the
// stack uses a separate callback. We return true (and fill *value) when we
// recognise the (object, property) pair, and false otherwise.
//
// THE errorCode OUT-PARAMETER. Every Get callback ends with uint32_t* errorCode.
// The stack PRESETS it to success (84) before the call, and reads it only if you
// return false. That gives a declining callback two distinct meanings:
//
//   1. return false and LEAVE errorCode ALONE  -> "I have no opinion on this
//      property." The stack falls back to its own handling (see below).
//   2. return false and SET *errorCode         -> "This read fails, with THIS
//      BACnet error." The client gets exactly that Error-PDU.
//
// WHAT false-WITHOUT-AN-ERROR-CODE ACTUALLY DOES - the most important paragraph
// in this file, and the opposite of what most people assume. It does NOT
// reliably produce a BACnet error. The stack only errors for the handful of
// properties it refuses to invent: Present_Value, Number_Of_States,
// Relinquish_Default, Local_Date, Local_Time, and a Network Port's APDU_Length.
// For EVERYTHING ELSE, a false return means the stack SILENTLY SUBSTITUTES a
// default:
//     Object_Name -> the literal string "undefined"
//     Units       -> no-units (95)
//     otherwise   -> a datatype zero-value
//
// This example never has a case where it knows a read is wrong (no out-of-range
// array index like B-SS's State_Text), so every callback below declines with
// *errorCode* left alone throughout.
// -----------------------------------------------------------------------------

// REAL (floating point) - the Analog Input's Present_Value.
bool GetPropertyReal(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     float* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;   // see "THE errorCode OUT-PARAMETER" above: we decline without naming an error
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_ANALOG_INPUT &&
        objectInstance == ANALOG_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        // ON REAL HARDWARE: return the live sensor reading here. Read it from a
        // cached variable that your hardware updates (as g_analogInput1Value is),
        // NOT directly from a slow/blocking device (I2C, SPI, ADC conversion):
        // this callback runs on the BACnetStack_Tick() thread, so blocking it
        // delays all BACnet processing. Sample the sensor on a timer/another
        // thread and just hand back the latest value from here.
        *value = g_analogInput1Value;
        return true;
    }
    return false;
}

// ENUMERATED - the Binary Input's Present_Value (0 = inactive, 1 = active), the
// Analog Input's Units, and Reliability on the two objects that report it.
bool GetPropertyEnumerated(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           uint32_t* value, const bool useArrayIndex,
                           const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_BINARY_INPUT &&
        objectInstance == BINARY_INPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            // ON REAL HARDWARE: return your cached input state here - the same rule
            // as GetPropertyReal above applies (never block this callback on slow
            // I/O; sample on a timer/another thread and hand back the latest).
            *value = 0; // inactive - the series-wide starting value
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_POLARITY) {
            *value = POLARITY_NORMAL; // required property of a Binary Input
            return true;
        }
    }
    // Units is REQUIRED on the Analog Input.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_UNITS &&
        objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) {
        *value = ENGINEERING_UNITS_DEGREES_CELSIUS;
        return true;
    }
    // Reliability is REQUIRED on Credential Data Input (cl. 12.36) - the one
    // object in this profile that lists it as required. This example never
    // synthesises a fault, so it always reports no-fault-detected.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_RELIABILITY &&
        objectType == OBJECT_TYPE_CREDENTIAL_DATA_INPUT && objectInstance == CREDENTIAL_DATA_INPUT_INSTANCE) {
        *value = RELIABILITY_NO_FAULT_DETECTED;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT &&
        objectInstance == NETWORK_PORT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_MODE) {
        *value = BACNET_IP_MODE_NORMAL; // not foreign-device, not BBMD
        return true;
    }
    return false;
}

// UNSIGNED INTEGER - the Multi-State Input's Present_Value, the Device's
// Vendor_Identifier, and (as a BACnet array-length request, arrayIndex 0) the
// element count of Credential Data Input's Supported_Formats array - the same
// pattern the Multi-State Input's State_Text uses below.
bool GetPropertyUnsignedInteger(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                uint32_t* value, const bool useArrayIndex,
                                const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)errorCode;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = 1; // state 1 (valid range is 1..Number_Of_States)
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_NUMBER_OF_STATES) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES; // required property
            return true;
        }
        // State_Text is an array. The stack asks for its LENGTH here (array
        // index 0) before reading each element via GetPropertyCharString.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT &&
            useArrayIndex && propertyArrayIndex == 0) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES;
            return true;
        }
    }
    if (objectType == OBJECT_TYPE_CREDENTIAL_DATA_INPUT &&
        objectInstance == CREDENTIAL_DATA_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_SUPPORTED_FORMATS &&
        useArrayIndex && propertyArrayIndex == 0) {
        *value = CREDENTIAL_SUPPORTED_FORMATS_COUNT;
        return true;
    }
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance &&
        propertyIdentifier == PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER) {
        *value = VENDOR_IDENTIFIER;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
        if (propertyIdentifier == PROPERTY_IDENTIFIER_APDU_LENGTH) {
            *value = MAX_APDU_LENGTH;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_REFERENCE_PORT) {
            *value = NETWORK_PORT_REFERENCE_PORT_NONE;
            return true;
        }
        if (propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT) {
            *value = g_bacnetIpUdpPort;
            return true;
        }
    }
    return false;
}

// BOOLEAN - Out_Of_Service, required on every input object and the Network
// Port, and (this example's one DS-WP-B target - see SetPropertyBool below)
// writable on the four input-family objects.
bool GetPropertyBool(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     bool* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (propertyIdentifier != PROPERTY_IDENTIFIER_OUT_OF_SERVICE) {
        return false;
    }
    if (objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) {
        *value = g_analogInputOutOfService;
        return true;
    }
    if (objectType == OBJECT_TYPE_BINARY_INPUT && objectInstance == BINARY_INPUT_INSTANCE) {
        *value = g_binaryInputOutOfService;
        return true;
    }
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT && objectInstance == MULTI_STATE_INPUT_INSTANCE) {
        *value = g_multiStateInputOutOfService;
        return true;
    }
    if (objectType == OBJECT_TYPE_CREDENTIAL_DATA_INPUT && objectInstance == CREDENTIAL_DATA_INPUT_INSTANCE) {
        *value = g_credentialDataInputOutOfService;
        return true;
    }
    // The Network Port never goes out of service in this example: always false.
    if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
        *value = false;
        return true;
    }
    return false;
}

// OCTET STRING - the Network Port's BACnet/IP addressing, AND Credential Data
// Input 1's Present_Value. The stack cannot know the host's IP, so the
// application must supply IP_Address / IP_Subnet_Mask / IP_Default_Gateway.
// Present_Value is served here because the stack wraps whatever bytes this
// callback returns into the BACnetAuthenticationFactor SEQUENCE's OCTET STRING
// value field (see the header comment at the top of this file) - this
// callback never constructs BACnet wire encoding itself, it only hands back
// raw application bytes either way.
bool GetPropertyOctetString(const uint32_t deviceInstance, const uint16_t objectType,
                            const uint32_t objectInstance, const uint32_t propertyIdentifier,
                            uint8_t* value, uint32_t* valueElementCount,
                            const uint32_t maxElementCount, const bool useArrayIndex,
                            const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_CREDENTIAL_DATA_INPUT &&
        objectInstance == CREDENTIAL_DATA_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        if (maxElementCount < CREDENTIAL_VALUE_LENGTH) {
            return false;
        }
        // Big-endian 4-byte card number - see g_credentialValue above.
        value[0] = (uint8_t)((g_credentialValue >> 24) & 0xFF);
        value[1] = (uint8_t)((g_credentialValue >> 16) & 0xFF);
        value[2] = (uint8_t)((g_credentialValue >> 8) & 0xFF);
        value[3] = (uint8_t)(g_credentialValue & 0xFF);
        *valueElementCount = CREDENTIAL_VALUE_LENGTH;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE &&
        maxElementCount >= 4) {
        const uint8_t* source = NULL;
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_IP_ADDRESS:         source = g_ipAddress; break;
            case PROPERTY_IDENTIFIER_IP_SUBNET_MASK:     source = g_ipSubnetMask; break;
            case PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY: source = g_ipDefaultGateway; break;
            default: return false;
        }
        memcpy(value, source, 4);
        *valueElementCount = 4;
        return true;
    }
    return false;
}

// TIME - Credential Data Input 1's Update_Time (REQUIRED, cl. 12.36). The
// stack wraps this into the BACnetTimeStamp CHOICE Update_Time actually needs
// on the wire - see the header comment at the top of this file. We report the
// wall-clock moment g_credentialValue last changed.
bool GetPropertyTime(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     uint8_t* hour, uint8_t* minute, uint8_t* second,
                     uint8_t* hundredthSecond, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex, uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance ||
        objectType != OBJECT_TYPE_CREDENTIAL_DATA_INPUT ||
        objectInstance != CREDENTIAL_DATA_INPUT_INSTANCE ||
        propertyIdentifier != PROPERTY_IDENTIFIER_UPDATE_TIME) {
        return false;
    }
#if defined(_WIN32)
    struct tm tmBuffer;
    localtime_s(&tmBuffer, &g_credentialUpdateTime);
    struct tm* local = &tmBuffer;
#else
    struct tm tmBuffer;
    struct tm* local = localtime_r(&g_credentialUpdateTime, &tmBuffer);
#endif
    *hour = (uint8_t)local->tm_hour;
    *minute = (uint8_t)local->tm_min;
    *second = (uint8_t)local->tm_sec;
    *hundredthSecond = 0; // time_t resolution is whole seconds
    return true;
}

// Supported_Formats (REQUIRED, cl. 12.36) - a BACnetAuthenticationFactorFormat
// ARRAY. This example's reader supports exactly one format: simple-number32
// (a plain numeric card ID), which is what GetPropertyOctetString above
// actually hands back as Present_Value's raw bytes. The stack calls this once
// per array element (propertyArrayIndex 1..N); the length request (index 0)
// is answered by GetPropertyUnsignedInteger above.
bool GetPropertyAuthenticationFactorFormat(const uint32_t deviceInstance, const uint16_t objectType,
                                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                           uint32_t* formatType, bool* useVendorId, uint32_t* vendorId,
                                           bool* useVendorFormat, uint32_t* vendorFormat,
                                           const bool useArrayIndex, const uint32_t propertyArrayIndex,
                                           uint32_t* errorCode) {
    (void)vendorId;
    (void)vendorFormat;
    (void)errorCode;
    if (deviceInstance != g_deviceInstance ||
        objectType != OBJECT_TYPE_CREDENTIAL_DATA_INPUT ||
        objectInstance != CREDENTIAL_DATA_INPUT_INSTANCE ||
        propertyIdentifier != PROPERTY_IDENTIFIER_SUPPORTED_FORMATS ||
        !useArrayIndex || propertyArrayIndex != 1) {
        return false;
    }
    *formatType = AUTHENTICATION_FACTOR_TYPE_SIMPLE_NUMBER32;
    *useVendorId = false;   // this format is a standard BACnet one, not vendor-specific
    *useVendorFormat = false;
    return true;
}

// Small helper: copy a C string into the stack's character-string buffer and
// set the element count + encoding. Returns true (so callers can `return`).
static bool ReturnCharacterString(const char* text, char* value,
                                  uint32_t* valueElementCount,
                                  const uint32_t maxElementCount,
                                  uint8_t* encodingType) {
    uint32_t length = (uint32_t)strlen(text);
    if (length > maxElementCount) {
        // Truncate SILENTLY to fit the stack's buffer. maxElementCount is
        // MAX_CHARACTER_STRING_SIZE (256 in this build), and our longest string
        // (DEVICE_DESCRIPTION) fits with room to spare - so this never trips
        // here. But if you build with STACK_OPTION_TARGET_EMBEDDED, that limit drops to
        // 64, and a long Object_Name or Description would be clipped mid-word
        // with nothing on the wire or console to tell you. If you lengthen any
        // served string, check it against MAX_CHARACTER_STRING_SIZE for your
        // target, or make this truncation loud.
        length = maxElementCount;
    }
    memcpy(value, text, length);
    *valueElementCount = length;
    *encodingType = CHARACTER_STRING_ENCODING_UTF8;
    return true;
}

// CHARACTER STRING - Object_Name for each object, and the device Description.
bool GetPropertyCharString(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           char* value, uint32_t* valueElementCount,
                           const uint32_t maxElementCount, uint8_t* encodingType,
                           const bool useArrayIndex, const uint32_t propertyArrayIndex,
                           uint32_t* errorCode) {
    (void)errorCode;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }

    // State_Text (optional) - one label per state of the Multi-State Input. It is
    // a BACnet array, so the stack asks for one element at a time by index
    // (1..Number_Of_States). Present_Value 1 -> "On", 2 -> "Off", 3 -> "Auto".
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT && useArrayIndex) {
        static const char* const stateText[] = { "On", "Off", "Auto" };
        if (propertyArrayIndex >= 1 && propertyArrayIndex <= MULTI_STATE_INPUT_NUMBER_OF_STATES) {
            return ReturnCharacterString(stateText[propertyArrayIndex - 1], value,
                                         valueElementCount, maxElementCount, encodingType);
        }
        return false;
    }

    // Object_Name - the colour name for each object.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_OBJECT_NAME) {
        if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
            return ReturnCharacterString(DEVICE_NAME, value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) {
            return ReturnCharacterString("Bronze", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_BINARY_INPUT && objectInstance == BINARY_INPUT_INSTANCE) {
            return ReturnCharacterString("Emerald", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT && objectInstance == MULTI_STATE_INPUT_INSTANCE) {
            return ReturnCharacterString("Hot Pink", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_CREDENTIAL_DATA_INPUT && objectInstance == CREDENTIAL_DATA_INPUT_INSTANCE) {
            return ReturnCharacterString("Flax", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
            return ReturnCharacterString("Vermilion", value, valueElementCount, maxElementCount, encodingType);
        }
    }

    // The remaining strings are all on the Device object - its identity, read
    // by clients and used to populate the device's I-Am / object list.
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_DESCRIPTION:
                return ReturnCharacterString(DEVICE_DESCRIPTION, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_VENDOR_NAME:
                return ReturnCharacterString(VENDOR_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_MODEL_NAME:
                return ReturnCharacterString(MODEL_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_FIRMWARE_REVISION:
                return ReturnCharacterString(g_firmwareRevision.c_str(), value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION:
                return ReturnCharacterString(APP_VERSION, value, valueElementCount, maxElementCount, encodingType);
            default:
                break;
        }
    }

    return false;
}

// -----------------------------------------------------------------------------
// 2b. Property "set" callback - this example's one DS-WP-B target
//
// None of this profile's objects has a profile-required writable property
// (Present_Value is read-only on every object here - see
// docs/property-profile-reference.md). What DS-WP-B demonstrates instead is
// the standard, spec-correct pattern of forcing an input object Out_Of_Service
// so a technician can substitute a manual value during commissioning or
// maintenance without a client seeing a stale/uninitialised reading. All four
// input-family objects accept it.
// -----------------------------------------------------------------------------

bool SetPropertyBool(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     const bool value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex, const uint8_t priority,
                     uint32_t* errorCode) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    (void)priority;    // Out_Of_Service is not commandable - no Priority_Array
    (void)errorCode;
    if (deviceInstance != g_deviceInstance || propertyIdentifier != PROPERTY_IDENTIFIER_OUT_OF_SERVICE) {
        return false;
    }
    const char* objectLabel = NULL;
    bool* target = NULL;
    if (objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) {
        target = &g_analogInputOutOfService; objectLabel = "Analog Input 1 (Bronze)";
    } else if (objectType == OBJECT_TYPE_BINARY_INPUT && objectInstance == BINARY_INPUT_INSTANCE) {
        target = &g_binaryInputOutOfService; objectLabel = "Binary Input 1 (Emerald)";
    } else if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT && objectInstance == MULTI_STATE_INPUT_INSTANCE) {
        target = &g_multiStateInputOutOfService; objectLabel = "Multi-State Input 1 (Hot Pink)";
    } else if (objectType == OBJECT_TYPE_CREDENTIAL_DATA_INPUT && objectInstance == CREDENTIAL_DATA_INPUT_INSTANCE) {
        target = &g_credentialDataInputOutOfService; objectLabel = "Credential Data Input 1 (Flax)";
    }
    if (target == NULL) {
        return false;
    }
    *target = value;
    printf("WriteProperty: %s Out_Of_Service <- %s\n", objectLabel, value ? "true" : "false");
    return true;
}

// -----------------------------------------------------------------------------
// 3. main()
// -----------------------------------------------------------------------------
int main(int argc, char** argv) {
    // Show printf output immediately, even when stdout is piped to a file.
    setvbuf(stdout, NULL, _IONBF, 0);

    // --- Load the CAS BACnet Stack -------------------------------------------
    // Required in every link mode (source/static/DLL) before any other
    // BACnetStack_* call - see CASBACnetStackAdapter.h. In DLL mode this is the
    // step that actually resolves the symbols; skipping it there is a null-pointer
    // call, not a silent no-op, so it comes before even --version (which calls
    // BACnetStack_GetAPIMajorVersion() to print the linked stack's version).
    if (!LoadBACnetFunctions()) {
        fprintf(stderr, "Error: failed to load the CAS BACnet Stack: %s\n",
                CASBACnetStackAdapter_LastError());
        return 1;
    }

    // g_firmwareRevision (Device object property 44) - see its own doc
    // comment above for why this is the STACK's version, not this example's
    // own (that's Application_Software_Version/APP_VERSION instead). Must
    // happen after LoadBACnetFunctions() (these getters ARE some of the
    // functions it loads) and before the Device object is ever readable.
    {
        char buf[32];
        snprintf(buf, sizeof(buf), "%u.%u.%u.%u",
                 BACnetStack_GetAPIMajorVersion(), BACnetStack_GetAPIMinorVersion(),
                 BACnetStack_GetAPIPatchVersion(), BACnetStack_GetAPIBuildVersion());
        g_firmwareRevision = buf;
    }

    // --- Command line + version --------------------------------------------
    // --help / --version print and exit, so handle them before we bind a socket.
    if (CASExampleHelper::HandleHelpAndVersionArgs(argc, argv, APP_NAME, APP_VERSION)) {
        return 0;
    }
    const uint16_t port = CASExampleHelper::ParsePortArg(argc, argv, 47808);
    g_deviceInstance = CASExampleHelper::ParseDeviceIdArg(argc, argv, g_deviceInstance);
    CASExampleHelper::PrintVersion(APP_NAME, APP_VERSION);

    // --- Bind the BACnet/IP socket -----------------------------------------
    if (!CASExampleHelper::SetupUDP(port)) {
        return 1;
    }

    // Capture the BACnet/IP addressing the Network Port object will report.
    g_bacnetIpUdpPort = port;
    if (!CASExampleHelper::GetLocalIPv4(g_ipAddress, g_ipSubnetMask)) {
        printf("FYI: could not read a local IPv4 address; Network Port IP_Address "
               "will report 0.0.0.0.\n");
    }

    // Seed Credential Data Input 1's Update_Time to "now" so its very first
    // read (and the initial COV notification a subscription triggers) reports
    // a real timestamp, not the epoch.
    g_credentialUpdateTime = time(NULL);

    // --- Register callbacks -------------------------------------------------
    // Tell the helper which Network Port object owns the socket it just bound.
    // The stack identifies a link by its Network Port INSTANCE, so the transport
    // callbacks (and the start-up I-Am) have to name the one added below.
    CASExampleHelper::SetNetworkPortInstance(NETWORK_PORT_INSTANCE);
    // The transport + time callbacks are shared boilerplate.
    CASExampleHelper::RegisterCommonCallbacks();
    // The property callbacks are specific to this example.
    BACnetStack_RegisterCallbackGetPropertyReal(GetPropertyReal);
    BACnetStack_RegisterCallbackGetPropertyEnumerated(GetPropertyEnumerated);
    BACnetStack_RegisterCallbackGetPropertyUnsignedInteger(GetPropertyUnsignedInteger);
    BACnetStack_RegisterCallbackGetPropertyCharacterString(GetPropertyCharString);
    BACnetStack_RegisterCallbackGetPropertyBool(GetPropertyBool);
    BACnetStack_RegisterCallbackGetPropertyOctetString(GetPropertyOctetString);
    BACnetStack_RegisterCallbackGetPropertyTime(GetPropertyTime);
    BACnetStack_RegisterCallbackGetPropertyAuthenticationFactorFormat(GetPropertyAuthenticationFactorFormat);
    // The "set" callback makes this a B-ACCR that executes DS-WP-B: it accepts
    // WriteProperty to Out_Of_Service on the four input-family objects.
    BACnetStack_RegisterCallbackSetPropertyBool(SetPropertyBool);

    // --- Create the device --------------------------------------------------
    if (!BACnetStack_AddDevice(g_deviceInstance)) {
        printf("Error: Failed to add the Device %u.\n", g_deviceInstance);
        return 1;
    }

    // Enable the services this profile requires: ReadProperty (DS-RP-B),
    // WriteProperty (DS-WP-B), and SubscribeCOV (DS-COV-B). We set them
    // explicitly to make the profile requirements obvious.
    //
    // We deliberately do NOT enable ReadPropertyMultiple, WritePropertyMultiple,
    // or any alarm/event/schedule service: a credential reader does not require
    // them, so a faithful B-ACCR example leaves them off.
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_READ_PROPERTY, true)) {
        printf("Error: Failed to enable the ReadProperty service.\n");
        return 1;
    }
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WRITE_PROPERTY, true)) {
        printf("Error: Failed to enable the WriteProperty service.\n");
        return 1;
    }
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_SUBSCRIBE_COV, true)) {
        printf("Error: Failed to enable the SubscribeCOV service.\n");
        return 1;
    }

    // Discovery: Who-Is/I-Am (DM-DDB-B) and Who-Has/I-Have (DM-DOB-B).
    //
    // These need enabling even though the device already ANSWERS them. The
    // stack's service defaults are whoIs + whoHas + readProperty only
    // (BACnetDBDevice.cpp) - iAm and iHave are left FALSE. Who-Is is answered and
    // the start-up I-Am is sent regardless, because neither is gated on the bit;
    // but Protocol_Services_Supported is emitted verbatim from that bitstring, so
    // without these calls the device DOES I-Am and I-Have while telling every
    // client it supports neither. The README claims DM-DDB-B and DM-DOB-B; this
    // is what makes the claim true on the wire.
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WHO_IS, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_I_AM, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_WHO_HAS, true) ||
        !BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_I_HAVE, true)) {
        printf("Error: Failed to enable the discovery services (Who-Is/I-Am, Who-Has/I-Have).\n");
        return 1;
    }

    // --- Add the read-only sensor objects -----------------------------------
    // Every stack setup call returns a bool; a real device should always check
    // it, so this example does too.
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT, ANALOG_INPUT_INSTANCE)) {
        printf("Error: Failed to add Analog Input %u (Bronze).\n", ANALOG_INPUT_INSTANCE);
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_BINARY_INPUT, BINARY_INPUT_INSTANCE)) {
        printf("Error: Failed to add Binary Input %u (Emerald).\n", BINARY_INPUT_INSTANCE);
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT, MULTI_STATE_INPUT_INSTANCE)) {
        printf("Error: Failed to add Multi-State Input %u (Hot Pink).\n", MULTI_STATE_INPUT_INSTANCE);
        return 1;
    }

    // --- Add the Credential Data Input object (the B-ACCR addition) ---------
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_CREDENTIAL_DATA_INPUT, CREDENTIAL_DATA_INPUT_INSTANCE)) {
        printf("Error: Failed to add Credential Data Input %u (Flax).\n", CREDENTIAL_DATA_INPUT_INSTANCE);
        return 1;
    }

    // --- Add the Network Port object ----------------------------------------
    // Every BACnet device (Protocol_Revision 17+) must have at least one Network
    // Port object describing the port it talks on. This one is the BACnet/IP
    // application port; it is the lowest layer, so its reference port is "none".
    // networkNumber 0 with quality "unknown" describes a local port that has not
    // learned its network number - the right answer for a device that is not a
    // router and has not been told one.
    if (!BACnetStack_AddNetworkPortObject(
            g_deviceInstance, NETWORK_PORT_INSTANCE,
            NETWORK_PORT_NETWORK_TYPE_IPV4,
            NETWORK_PORT_PROTOCOL_LEVEL_BACNET_APPLICATION,
            0,  // networkNumber: not configured
            NETWORK_NUMBER_QUALITY_UNKNOWN,
            NETWORK_PORT_REFERENCE_PORT_NONE)) {
        printf("Error: Failed to add Network Port 1 (Vermilion).\n");
        return 1;
    }

    // --- Enable the OPTIONAL properties we choose to expose ------------------
    // The stack automatically enables an object's REQUIRED properties when the
    // object is added (AddObject / AddNetworkPortObject) - so Units, Polarity,
    // Number_Of_States, Out_Of_Service, Present_Value, Status_Flags,
    // Supported_Formats, Update_Time, and the Network Port's BACnet/IP
    // addressing (IP_Address, IP_Subnet_Mask, BACnet_IP_UDP_Port, ...) are
    // already enabled; our Get* callbacks just supply their values. Only
    // OPTIONAL properties need SetPropertyEnabled: State_Text on the
    // Multi-State Input. (Reliability is required on Credential Data Input,
    // not optional, so it needs no enable there - the stack already enabled
    // it when the object was added.)
    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_DEVICE,
                                        g_deviceInstance, PROPERTY_IDENTIFIER_DESCRIPTION, true)) {
        printf("Error: Failed to enable Description on the Device object.\n");
        return 1;
    }
    if (!BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT,
                                        MULTI_STATE_INPUT_INSTANCE, PROPERTY_IDENTIFIER_STATE_TEXT, true)) {
        printf("Error: Failed to enable State_Text on Multi-State Input 1 (Hot Pink).\n");
        return 1;
    }

    // --- THE F-COV PATTERN: make Present_Value subscribable, then bound the
    // subscription table -----------------------------------------------------
    // This repo is the series' canonical source for SubscribeCOV. Two calls:
    //
    //   1. BACnetStack_SetPropertySubscribable - per object, on the property a
    //      client will watch. The doc comment on this export says the
    //      "standard COV object types" (analog/binary/multi-state/life-safety/
    //      character-string value and the rest of 135-2024 Table 13-1) already
    //      accept a plain SubscribeCOV WITHOUT this call - so the Analog Input
    //      call below is technically redundant. It is made anyway, for two
    //      reasons worth keeping when you copy this pattern: it states the
    //      subscribable contract in one visible place (see the same rationale
    //      in B-SA's commandable-outputs loop), and Credential Data Input is
    //      NOT one of the standard COV-reporting types - for THAT object this
    //      call is not cosmetic, it is the only thing that makes
    //      SubscribeCOV(Flax) succeed instead of failing.
    //
    //   2. BACnetStack_SetCOVSettings - bounds the device's COV subscription
    //      table: how many active subscriptions it will hold, and the longest
    //      lifetime (seconds) it will grant one. 0 subscriptions = no limit;
    //      28800 seconds (8 hours) is the stack's own default lifetime bound,
    //      named here explicitly so the number in this file matches the
    //      number a wire capture will show.
    //
    //   CREDENTIAL DATA INPUT'S SUBSCRIBABLE PROPERTY IS Update_Time, NOT
    //   Present_Value - read this before copying the AI1 call below as a
    //   template. A plain SubscribeCOV (as opposed to SubscribeCOVProperty,
    //   which names an arbitrary property explicitly) does not let the client
    //   choose which property to monitor - the SERVER decides, per object
    //   type, per 135-2024 Table 13-1. For most types that is Present_Value;
    //   for Credential Data Input the standard's own COV column says "if
    //   Update_Time changes at all, or Status_Flags changes at all" - NOT
    //   Present_Value (verified against the stack's own
    //   BACnetSubscribeCOVProcessor::GetSubscriptionProperty(), which returns
    //   BACnetPropertyIdentifier::updateTime for credentialDataInput and
    //   presentValue for everything else). So the property this example makes
    //   subscribable on Credential Data Input 1 is Update_Time - calling
    //   SetPropertySubscribable on its Present_Value instead compiles, runs,
    //   and returns true, but a client's plain SubscribeCOV then fails with
    //   Error(subscribe-cov): property: not-cov-property, because the stack
    //   is checking a DIFFERENT property's subscribable flag than the one
    //   that got set - confirmed on the wire while building this example.
    //   The notification content is unaffected by this distinction: it still
    //   carries Present_Value + Status_Flags + Update_Time (see "Verify" in
    //   the README) - Update_Time is only the trigger condition, not the only
    //   payload field.
    if (!BACnetStack_SetPropertySubscribable(g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT,
                                             ANALOG_INPUT_INSTANCE, PROPERTY_IDENTIFIER_PRESENT_VALUE, true)) {
        printf("Error: Failed to make Analog Input 1 (Bronze) Present_Value subscribable.\n");
        return 1;
    }
    if (!BACnetStack_SetPropertySubscribable(g_deviceInstance, OBJECT_TYPE_CREDENTIAL_DATA_INPUT,
                                             CREDENTIAL_DATA_INPUT_INSTANCE, PROPERTY_IDENTIFIER_UPDATE_TIME, true)) {
        printf("Error: Failed to make Credential Data Input 1 (Flax) Update_Time subscribable.\n");
        return 1;
    }
    if (!BACnetStack_SetCOVSettings(g_deviceInstance, 0, 28800)) {
        printf("Error: Failed to configure COV settings.\n");
        return 1;
    }

    // --- Make Out_Of_Service writable on the four input-family objects ------
    // (This example's DS-WP-B demonstration - see the comment above
    // SetPropertyBool.) Out_Of_Service defaults to required-but-not-writable;
    // SetPropertyWritable is what actually lets a client's WriteProperty reach
    // our SetPropertyBool callback instead of getting write-access-denied.
    struct WritableObject { uint16_t type; uint32_t instance; const char* label; };
    const WritableObject writableObjects[] = {
        { OBJECT_TYPE_ANALOG_INPUT,          ANALOG_INPUT_INSTANCE,          "Analog Input 1 (Bronze)" },
        { OBJECT_TYPE_BINARY_INPUT,          BINARY_INPUT_INSTANCE,          "Binary Input 1 (Emerald)" },
        { OBJECT_TYPE_MULTI_STATE_INPUT,     MULTI_STATE_INPUT_INSTANCE,     "Multi-State Input 1 (Hot Pink)" },
        { OBJECT_TYPE_CREDENTIAL_DATA_INPUT, CREDENTIAL_DATA_INPUT_INSTANCE, "Credential Data Input 1 (Flax)" },
    };
    for (size_t i = 0; i < sizeof(writableObjects) / sizeof(writableObjects[0]); ++i) {
        if (!BACnetStack_SetPropertyWritable(g_deviceInstance, writableObjects[i].type,
                                             writableObjects[i].instance,
                                             PROPERTY_IDENTIFIER_OUT_OF_SERVICE, true)) {
            printf("Error: Failed to make Out_Of_Service writable on %s.\n", writableObjects[i].label);
            return 1;
        }
    }

    // Who-Is is answered automatically. The spec also requires a device to
    // announce itself on start-up, so broadcast an unsolicited I-Am now (to the
    // local subnet broadcast - the Network Port's own network).
    CASExampleHelper::SendIAm(g_deviceInstance);

    printf("FYI: Device %u (\"%s\") ready. Vendor ID %u. Press 'h' for help.\n",
           g_deviceInstance, DEVICE_NAME, VENDOR_IDENTIFIER);

    // --- Run the stack ------------------------------------------------------
    // BACnetStack_Tick() processes incoming messages and timers. Call it
    // continuously, and poll the keyboard for interactive commands.
    bool running = true;
    while (running) {
        BACnetStack_Tick();

        switch (CASExampleHelper::PollKey()) {
            case CASExampleHelper::KeyCommand::Help:
                CASExampleHelper::PrintHelp(APP_NAME, APP_VERSION);
                break;
            case CASExampleHelper::KeyCommand::Quit:
                running = false;
                break;
            case CASExampleHelper::KeyCommand::ArrowUp:
                // Nudge Analog Input 1 (Bronze), as every example in the series
                // does with this key - then, THE F-COV PAYOFF: tell the stack
                // the value changed so it evaluates COV subscriptions and fires
                // a notification if anyone is subscribed. Without this call the
                // new value would only reach a client on its next poll.
                g_analogInput1Value += 1.1f;
                printf("Analog Input 1 (Bronze) = %.1f C\n", g_analogInput1Value);
                BACnetStack_UpdateValue(g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT,
                                        ANALOG_INPUT_INSTANCE, PROPERTY_IDENTIFIER_PRESENT_VALUE);
                // Also simulate a new credential presentation at the door -
                // Credential Data Input 1 (Flax) is this repo's OTHER
                // COV-subscribable object, and its whole point is to push a
                // change like this to subscribers instead of waiting to be
                // polled. A real reader would call this from its hardware
                // ISR/callback instead of a keypress.
                //
                // UpdateValue names Update_Time, not Present_Value, here - see
                // the long comment above the SetPropertySubscribable calls in
                // main(): Update_Time is the property the stack's plain
                // SubscribeCOV actually monitors for a Credential Data Input,
                // per 135-2024 Table 13-1. Present_Value still changed too
                // (g_credentialValue, above) and still rides along in the
                // notification payload - it is just not what triggers it.
                g_credentialValue++;
                g_credentialUpdateTime = time(NULL);
                printf("Credential Data Input 1 (Flax) presented card 0x%08X\n", g_credentialValue);
                BACnetStack_UpdateValue(g_deviceInstance, OBJECT_TYPE_CREDENTIAL_DATA_INPUT,
                                        CREDENTIAL_DATA_INPUT_INSTANCE, PROPERTY_IDENTIFIER_UPDATE_TIME);
                break;
            case CASExampleHelper::KeyCommand::ArrowDown:
                g_analogInput1Value -= 1.1f;
                printf("Analog Input 1 (Bronze) = %.1f C\n", g_analogInput1Value);
                BACnetStack_UpdateValue(g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT,
                                        ANALOG_INPUT_INSTANCE, PROPERTY_IDENTIFIER_PRESENT_VALUE);
                g_credentialValue--;
                g_credentialUpdateTime = time(NULL);
                printf("Credential Data Input 1 (Flax) presented card 0x%08X\n", g_credentialValue);
                BACnetStack_UpdateValue(g_deviceInstance, OBJECT_TYPE_CREDENTIAL_DATA_INPUT,
                                        CREDENTIAL_DATA_INPUT_INSTANCE, PROPERTY_IDENTIFIER_UPDATE_TIME);
                break;
            case CASExampleHelper::KeyCommand::None:
            default:
                break;
        }

#if defined(_WIN32)
        Sleep(1); // 1 ms - be a good citizen, don't spin the CPU
#else
        usleep(1000);
#endif
    }

    CASExampleHelper::RestoreInput();
    CASExampleHelper::ShutdownUDP();
    return 0;
}
